macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  env:
    DTHK_PLATFORM: macos
    DTHK_ARCH: aarch64
  script: |
    # install babashka
    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    ./install --dir ${HOME}/.local/bin
    export PATH=${HOME}/.local/bin:$PATH

    # install clojure
    curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
    chmod +x posix-install.sh
    sudo ./posix-install.sh

    # install graalvm
    curl -L -O https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_${DTHK_PLATFORM}-${DTHK_ARCH}_bin.tar.gz
    sudo xattr -r -d com.apple.quarantine graalvm-jdk-21_${DTHK_PLATFORM}-${DTHK_ARCH}_bin.tar.gz
    tar -xzf graalvm-jdk-21_macos-${DTHK_ARCH}_bin.tar.gz
    sudo mv graalvm-jdk-21_macos-${DTHK_ARCH} /Library/Java/JavaVirtualMachines
    /usr/libexec/java_home -V
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/<graalvm>/Contents/Home
    export PATH=/Library/Java/JavaVirtualMachines/<graalvm>/Contents/Home/bin:$PATH
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version

    # compile
    bb ni-cli

    # upload artifact
    bb release native-cli
  binaries_artifacts:
    path: "dist/*"
