# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: alice
          POSTGRES_PASSWORD: foo
          POSTGRES_DB: config-test

    working_directory: ~/datahike

    environment:
      LEIN_ROOT: nbd
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - datahike-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            #- v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: datahike-{{ checksum "project.clj" }}

      # run tests!
      - run: lein do test, uberjar

      - run: lein kaocha integration
