version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build-and-deploy:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: build-and-deploy
          command: clojure -T:build ci

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
          setup_cljs: false
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/backward-compatibility-test:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest-postgresql:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - build-and-deploy:
          context: dockerhub-deploy
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/backward-compatibility-test
            - tools/integrationtest-postgresql
