version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: clean
          command: clojure -T:build clean
      - run:
          name: jar
          command: clojure -T:build jar
  deploy:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - add_ssh_keys:
          fingerprints:
            - "ba:37:bf:3e:12:f2:d6:43:c7:a2:ec:81:b7:2e:09:61"
      - run:
          name: tag
          command: clojure -T:build tag
      - run:
          name: deploy
          command: clojure -T:build deploy

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
          setup_cljs: false
      - build:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/backward-compatibility-test:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest-postgresql:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - deploy:
          context:
            - dockerhub-deploy
            - clojars-deploy
          filters:
            branches:
              only: switch-to-tools-build
          requires:
            - tools/setup
            - tools/format
            - tools/unittest
            - tools/backward-compatibility-test
            - tools/integrationtest-postgresql
