name: Building native images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
      - '.github/**'
      - '.circleci/**'
      - 'bb/**'
      - 'dev/**'
      - 'examples/**'
      - 'test/**'

jobs:
  native:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        include:
          - os: macos-13
            name: macos
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GRAALVM_VERSION: 24.0.1
      DTHK_PLATFORM: macos
      DTHK_ARCH: amd64
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'

      - name: Cache deps
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Eat this!!!
        run: |
          arch
          uname -m

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.12.1.1550
          bb: 1.12.204

      - name: Build native image
        run: bb ni-cli

      - name: Test native image
        run: |
          bb test native-image
          bb test bb-pod

      - name: Release native-image
        run: bb release native-cli
